### ISSUE TITLE
Heroku dependency should be optional

### ISSUE THREAD

**Issue by ballPointPenguin** [pol-is/polis-deploy#5]
In its current form, the server code is pointing to a Heroku endpoint for Postgresql database.
We should consider parameterizing this and/or controlling with environment variables to allow for alternative database locations (e.g. local docker).

cc: @metasoarous

**Comment by metasoarous** [comment]
Oh; Is it still pointing to the heroku db? I thought we did get it to point to the docker db.

**Comment by patcon** [comment]
What's needed to act on this or close it out? @ballPointPenguin is there anything you can think of to move this forward?

**Comment by metasoarous** [comment]
Isn't this one of the environment variables now?

**Comment by patcon** [comment]
Yeah, I think so:

https://github.com/pol-is/polisServer/blob/e7cfae02efd99197d48d1a3fe29ddd2960562553/Dockerfile#L11

@ballPointPenguin we good to close this?

**Comment by ballPointPenguin** [comment]
Yes. Thanks.
